---
title: "tidyverse"
format: html
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
```


```{r}
tb <- tribble(
    ~a, ~'b c', ~'group(a very long name:)',
    1, 2, 'a',
    3, 4, 'b'
)
tb
# # A tibble: 2 × 3
#       a `b c` `group(a very long name:)`
#   <dbl> <dbl> <chr>                     
# 1     1     2 a                         
# 2     3     4 b    

# 自动把所有列名改为符合R语言变量名语法的名称
tb <- janitor::clean_names(tb)
tb
# # A tibble: 2 × 3
#       a   b_c group_a_very_long_name
#   <dbl> <dbl> <chr>                 
# 1     1     2 a                     
# 2     3     4 b       

# 重命名个别列
tb <- tb |> rename(grp = group_a_very_long_name)
tb
# # A tibble: 2 × 3
#       a   b_c grp  
#   <dbl> <dbl> <chr>
# 1     1     2 a    
# 2     3     4 b

# 一步完成
tb <- tb |>
    janitor::clean_names() |>
    rename(grp = group_a_very_long_name)


iris <- tibble(iris) |>
    rename_with(\(x)  str_to_lower(str_replace(x, '\\.', '_')))
iris
# # A tibble: 150 × 5
#    sepal_length sepal_width petal_length petal_width species
#           <dbl>       <dbl>        <dbl>       <dbl> <fct>  
#  1          5.1         3.5          1.4         0.2 setosa 
#  2          4.9         3            1.4         0.2 setosa 
#  3          4.7         3.2          1.3         0.2 setosa 
#  4          4.6         3.1          1.5         0.2 setosa 
#  5          5           3.6          1.4         0.2 setosa 
#  6          5.4         3.9          1.7         0.4 setosa 
#  7          4.6         3.4          1.4         0.3 setosa 
#  8          5           3.4          1.5         0.2 setosa 
#  9          4.4         2.9          1.4         0.2 setosa 
# 10          4.9         3.1          1.5         0.1 setosa

# 算前两列的均值
iris |> summarize(mean_sepal_length = mean(sepal_length),
                  mean_sepal_width = mean(sepal_width))
#   mean_sepal_length mean_sepal_width
#               <dbl>            <dbl>
# 1              5.84             3.06

# 按照物种（species列）分组，分别算sepal_length跟sepal_width的均值
iris |>
    group_by(species) |> 
    summarize(mean_sepal_length = mean(sepal_length),
              mean_sepal_width = mean(sepal_width))
# 或：
iris |>
    summarize(mean_sepal_length = mean(sepal_length),
              mean_sepal_width = mean(sepal_width),
              .by = c(species))  # 单个变量可以不用c()
#  # A tibble: 3 × 3
#   species    mean_sepal_length mean_sepal_width
#   <fct>                  <dbl>            <dbl>
# 1 setosa                  5.01             3.43
# 2 versicolor              5.94             2.77
# 3 virginica               6.59             2.97

# 用同一个函数summarize所有列
iris |>
    group_by(species) |> 
    summarize(across(everything(), mean))
# # A tibble: 3 × 5
#   species    sepal_length sepal_width petal_length petal_width
#   <fct>             <dbl>       <dbl>        <dbl>       <dbl>
# 1 setosa             5.01        3.43         1.46       0.246
# 2 versicolor         5.94        2.77         4.26       1.33 
# 3 virginica          6.59        2.97         5.55       2.03 

# 用同一个函数summarize部分列
iris |>
    group_by(species) |> 
    summarize(across(sepal_length:petal_length, mean))
# # A tibble: 3 × 4
#   species    sepal_length sepal_width petal_length
#   <fct>             <dbl>       <dbl>        <dbl>
# 1 setosa             5.01        3.43         1.46
# 2 versicolor         5.94        2.77         4.26
# 3 virginica          6.59        2.97         5.55


# 用同一个函数summarize部分列,并改变列名
iris |>
    group_by(species) |> 
    summarize(across(starts_with('sepal'), mean, .names = 'mean_{.col}'))
#   species    mean_sepal_length mean_sepal_width
#   <fct>                  <dbl>            <dbl>
# 1 setosa                  5.01             3.43
# 2 versicolor              5.94             2.77
# 3 virginica               6.59             2.97

# 当然也可以用多个函数summarize多个列
iris |>
    group_by(species) |> 
    summarize(across(starts_with('sepal'),
                     list(avg = mean, sd = sd),
                     .names = '{.fn}_{.col}'))
# # A tibble: 3 × 5
#   species    avg_sepal_length sd_sepal_length avg_sepal_width sd_sepal_width
#   <fct>                 <dbl>           <dbl>           <dbl>          <dbl>
# 1 setosa                 5.01           0.352            3.43          0.379
# 2 versicolor             5.94           0.516            2.77          0.314
# 3 virginica              6.59           0.636            2.97          0.322
```

```{r}
# 长数据框 与 宽数据框 之间的变换

df_long <- tribble(
  ~id, ~measurement, ~value,
  "A", "bp1",        100,
  "A", "bp2",        120,
  "B", "bp1",        140,
  "B", "bp2",        115,
  "C", "bp1",        120,
  "C", "bp2",        125
)
# # A tibble: 6 × 3
#   id    measurement value
#   <chr> <chr>       <dbl>
# 1 A     bp1           100
# 2 A     bp2           120
# 3 B     bp1           140
# 4 B     bp2           115
# 5 C     bp1           120
# 6 C     bp2           125

# long to wide
df_wide <- df_long |> pivot_wider(names_from = measurement, values_from = value)
df_wide
# # A tibble: 3 × 3
#   id      bp1   bp2
#   <chr> <dbl> <dbl>
# 1 A       100   120
# 2 B       140   115
# 3 C       120   125

# wide to long
df_wide |> pivot_longer(bp1:bp2, names_to = 'measurement', values_to = 'value')
# # A tibble: 6 × 3
#   id    measurement value
#   <chr> <chr>       <dbl>
# 1 A     bp1           100
# 2 A     bp2           120
# 3 B     bp1           140
# 4 B     bp2           115
# 5 C     bp1           120
# 6 C     bp2           125

# 长变宽可以对指定values来自多个列
# long to wide with values from multiple columns
df_wide |> pivot_wider(names_from = id, values_from = bp1:bp2)
#   bp1_A bp1_B bp1_C bp2_A bp2_B bp2_C
#   <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
# 1   100   140   120   120   115   125

# adjust final column names
# here {.value} refers to column name of values_from colums (bp1, bp2),
# {variable} refers to column values of names_from column (id), that is, {variable} is in set {A, B, C}.
df_wider <- df_wide |> pivot_wider(names_from = id, values_from = bp1:bp2, names_glue = '{id}__{.value}')
df_wider
#   A__bp1 B__bp1 C__bp1 A__bp2 B__bp2 C__bp2
#    <dbl>  <dbl>  <dbl>  <dbl>  <dbl>  <dbl>
# 1    100    140    120    120    115    125

# 宽变长的时候，原本的列名会变成1列，但可以通过names_sep或names_pattern将这个存储原来列名
# 的列进一步拆分成不同的列
# revert
# names_sep determines how column names like A__bp1, A__bp2, ... are
# separate into two columns of id and measurment
df_wider |> pivot_longer(A__bp1:C__bp2, names_to = c('id', 'measurement'), names_sep = '__')
#   id    measurement value
#   <chr> <chr>       <dbl>
# 1 A     bp1           100
# 2 B     bp1           140
# 3 C     bp1           120
# 4 A     bp2           120
# 5 B     bp2           115
# 6 C     bp2           125

# alternatively, specify separate of column names with regular expression
# first group to id, while the other to measurement
df_wider |> pivot_longer(
    A__bp1:C__bp2,
    names_to = c('id', 'measurement'),
    names_pattern = '(.*)__(.*)')
#   id    measurement value
#   <chr> <chr>       <dbl>
# 1 A     bp1           100
# 2 B     bp1           140
# 3 C     bp1           120
# 4 A     bp2           120
# 5 B     bp2           115
# 6 C     bp2           125
```

```{r}
tb <- tribble(~sample, 'female_control', 'female_starvation', 'male_control', 'male_starvation')
tb
# # A tibble: 4 × 1
#   sample           
#   <chr>            
# 1 female_control   
# 2 female_starvation
# 3 male_control     
# 4 male_starvation

tb |> separate_wider_delim(sample, delim = '_', names = c('sex', 'condition'))
# # A tibble: 4 × 2
#   sex    condition 
#   <chr>  <chr>     
# 1 female control   
# 2 female starvation
# 3 male   control   
# 4 male   starvation

tb <- tribble(
    ~grade, ~student,
    'A', 'Xiyangyang,Conan',
    'B', 'Tom,Jerry',
    'C', 'Garfield'
)
tb |> separate_longer_delim(student, delim = ',')
# # A tibble: 5 × 2
#   grade student   
#   <chr> <chr>     
# 1 A     Xiyangyang
# 2 A     Conan     
# 3 B     Tom       
# 4 B     Jerry     
# 5 C     Garfield  
```

```{r}
# 对多列进行操作
# pick与across互补：
# - across对很多列进行操作，对其中每一列应用某个函数；
#- pick也对很多列进行操作，但是是对整个被选中的列组成的data frame应用某个函数
mtcars |> mutate(mean = rowMeans(pick(mpg:drat)))

mtcars |> mutate(across(mpg:drat, ~ .x + 2))
```

